--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/JoinACM
build-by-default: true
branches:
- main
projects:
  JoinACM:
    path: ""
    icon: "icon.png"
    lint:
      phpstan: false
...
