--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/JoinACM
build-by-default: true
branches:
- PM5
- stable
projects:
  JoinACM:
    path: ""
    icon: "icon-joinacm.png"
    libs:
      - src: ACM-PocketMine-MP/Commando/Commando
        version: ^3.2.1
        branch: PM5
      - src: muqsit/simplepackethandler/SimplePacketHandler
        version: ^0.1.3
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.3
      - src: ACM-PocketMine-MP/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^2.0.0
      - src: cooldogepm/libBook/libBook
        version: ^0.0.2
    lint:
      phpstan: false
...
