name: JoinACM
main: fernanACM\JoinACM\Loader
version: 3.0.0
api: 5.0.0
author: fernanACM
description: Simple custom JoinUI for PocketMine-MP 4.0 by fernanACM
website: https://github.com/fernanACM

permissions:
  joinacm.command:
    description: /joinacm
    default: op
  joinacm.command.setspawn:
    description: /joinacm setspawn
    default: op
  joinacm.command.removespawn:
    description: /joinacm removespawn
    default: op