name: JoinACM
main: fernanACM\JoinACM\Loader
version: 2.0.1
api: 4.0.0
author: fernanACM
description: Simple custom JoinUI for PocketMine-MP 4.0 by fernanACM
website: https://github.com/fernanACM

permissions:
  joinacm.command:
    description: /joinacm
    default: op
  joinacm.command.setspawn:
    description: /joinacm setspawn
    default: op
  joinacm.command.removespawn:
    description: /joinacm removespawn
    default: op